#> This function is generated by generator
tag @s add boomber.framework.block.fish_bowl.small_empty
function boomber:framework/trait/block/implement
function boomber:framework/trait/fish_bowl/implement
function boomber:framework/trait/entity/template/finalize