#> This function is generated by generator
execute if entity @e[tag=boomber.framework.trait.chair, distance=..0.3] run function boomber:framework/trait/item_frame_block/block/chair/gaming_chair/fail
execute unless entity @e[tag=boomber.framework.trait.chair, distance=..0.3] run function boomber:framework/trait/item_frame_block/block/chair/gaming_chair/success