#> This function is generated by generator
tag @s add boomber.framework.block.chair.gaming_chair
function boomber:framework/trait/block/implement
function boomber:framework/trait/gaming_chair/implement
function boomber:framework/trait/chair/implement
function boomber:framework/trait/entity/template/finalize