#> This function is generated by generator
tag @s add boomber.framework.block.fridge.quartz
function boomber:framework/trait/block/implement
function boomber:framework/trait/solid_block/implement
function boomber:framework/trait/fridge/implement
function boomber:framework/trait/entity/template/finalize