#> This function is generated by generator
tag @s add boomber.framework.block.doormat.creeper
function boomber:framework/trait/block/implement
function boomber:framework/trait/doormat/implement
function boomber:framework/trait/entity/template/finalize