#> This function is generated by generator
execute if entity @e[tag=boomber.framework.trait.gravestone, distance=..0.3] run function boomber:framework/trait/item_frame_block/block/gravestone/cross.wood/fail
execute unless entity @e[tag=boomber.framework.trait.gravestone, distance=..0.3] run function boomber:framework/trait/item_frame_block/block/gravestone/cross.wood/success