#> This function is generated by generator
tag @s add boomber.framework.block.gravestone.celtic.stone
function boomber:framework/trait/block/implement
function boomber:framework/trait/gravestone/implement
function boomber:framework/trait/entity/template/finalize