#> This function is generated by generator
execute if entity @s[tag=boomber.framework.block.gravestone.plate] run loot spawn ~ ~ ~ loot boomber:framework/item/gravestone/plate
execute if entity @s[tag=boomber.framework.block.gravestone.cross] run loot spawn ~ ~ ~ loot boomber:framework/item/gravestone/cross
execute if entity @s[tag=boomber.framework.block.gravestone.celtic] run loot spawn ~ ~ ~ loot boomber:framework/item/gravestone/celtic
kill @s