#> This function is generated by generator
execute if entity @s[tag=boomber.framework.block.gravestone.plate.stone] run loot spawn ~ ~ ~ loot boomber:framework/item/gravestone/plate.stone
execute if entity @s[tag=boomber.framework.block.gravestone.plate.overgrown_stone] run loot spawn ~ ~ ~ loot boomber:framework/item/gravestone/plate.overgrown_stone
execute if entity @s[tag=boomber.framework.block.gravestone.cross.stone] run loot spawn ~ ~ ~ loot boomber:framework/item/gravestone/cross.stone
execute if entity @s[tag=boomber.framework.block.gravestone.cross.overgrown_stone] run loot spawn ~ ~ ~ loot boomber:framework/item/gravestone/cross.overgrown_stone
execute if entity @s[tag=boomber.framework.block.gravestone.cross.wood] run loot spawn ~ ~ ~ loot boomber:framework/item/gravestone/cross.wood
execute if entity @s[tag=boomber.framework.block.gravestone.cross.overgrown_wood] run loot spawn ~ ~ ~ loot boomber:framework/item/gravestone/cross.overgrown_wood
execute if entity @s[tag=boomber.framework.block.gravestone.celtic.stone] run loot spawn ~ ~ ~ loot boomber:framework/item/gravestone/celtic.stone
execute if entity @s[tag=boomber.framework.block.gravestone.celtic.overgrown_stone] run loot spawn ~ ~ ~ loot boomber:framework/item/gravestone/celtic.overgrown_stone
kill @s