#> This function is generated by generator
tag @s add boomber.framework.block.drawer.dark_oak
function boomber:framework/trait/block/implement
function boomber:framework/trait/solid_block/implement
function boomber:framework/trait/drawer/implement
function boomber:framework/trait/entity/template/finalize