#> This function is generated by generator
tag @s add boomber.framework.block.torch_decorator.candle
function boomber:framework/trait/block/implement
function boomber:framework/trait/torch_decorator/implement
function boomber:framework/trait/entity/template/finalize