#> This function is generated by generator
tag @s add boomber.framework.block.undefined.candle
function boomber:framework/trait/block/implement
function boomber:framework/trait/undefined/implement
function boomber:framework/trait/entity/template/finalize