#> This function is generated by generator
execute if entity @s[tag=boomber.framework.block.drawer.oak] run loot spawn ~ ~ ~ loot boomber:framework/item/drawer/oak
execute if entity @s[tag=boomber.framework.block.drawer.spruce] run loot spawn ~ ~ ~ loot boomber:framework/item/drawer/spruce
execute if entity @s[tag=boomber.framework.block.drawer.birch] run loot spawn ~ ~ ~ loot boomber:framework/item/drawer/birch
execute if entity @s[tag=boomber.framework.block.drawer.jungle] run loot spawn ~ ~ ~ loot boomber:framework/item/drawer/jungle
execute if entity @s[tag=boomber.framework.block.drawer.acacia] run loot spawn ~ ~ ~ loot boomber:framework/item/drawer/acacia
execute if entity @s[tag=boomber.framework.block.drawer.dark_oak] run loot spawn ~ ~ ~ loot boomber:framework/item/drawer/dark_oak
kill @s