#> This function is generated by generator
execute if entity @s[tag=boomber.framework.block.fridge.quartz] run loot spawn ~ ~ ~ loot boomber:framework/item/fridge/quartz
execute if entity @s[tag=boomber.framework.block.fridge.black] run loot spawn ~ ~ ~ loot boomber:framework/item/fridge/black
kill @s