#> This function is generated by generator
tag @s add boomber.framework.block.kitchen_counter.modern
function boomber:framework/trait/block/implement
function boomber:framework/trait/solid_block/implement
function boomber:framework/trait/kitchen_counter/implement
function boomber:framework/trait/entity/template/finalize