#> This function is generated by generator
execute if entity @e[tag=boomber.framework.trait.doormat, distance=..0.3] run function boomber:framework/trait/item_frame_block/block/doormat/light_gray_wool/fail
execute unless entity @e[tag=boomber.framework.trait.doormat, distance=..0.3] run function boomber:framework/trait/item_frame_block/block/doormat/light_gray_wool/success