#> This function is generated by generator
execute if entity @e[tag=boomber.framework.trait.figure, distance=..0.3] run function boomber:framework/trait/item_frame_block/block/figure/megumin/fail
execute unless entity @e[tag=boomber.framework.trait.figure, distance=..0.3] run function boomber:framework/trait/item_frame_block/block/figure/megumin/success