#> This function is generated by generator
tag @s add boomber.framework.block.figure.megumin
function boomber:framework/trait/block/implement
function boomber:framework/trait/figure/implement
function boomber:framework/trait/entity/template/finalize