#> This function is generated by generator
execute if entity @s[tag=boomber.framework.block.doormat.creeper] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/creeper
execute if entity @s[tag=boomber.framework.block.doormat.megumin] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/megumin
execute if entity @s[tag=boomber.framework.block.doormat.chicken] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/chicken
execute if entity @s[tag=boomber.framework.block.doormat.tnt] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/tnt
execute if entity @s[tag=boomber.framework.block.doormat.white_wool] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/white_wool
execute if entity @s[tag=boomber.framework.block.doormat.orange_wool] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/orange_wool
execute if entity @s[tag=boomber.framework.block.doormat.magenta_wool] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/magenta_wool
execute if entity @s[tag=boomber.framework.block.doormat.light_blue_wool] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/light_blue_wool
execute if entity @s[tag=boomber.framework.block.doormat.yellow_wool] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/yellow_wool
execute if entity @s[tag=boomber.framework.block.doormat.lime_wool] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/lime_wool
execute if entity @s[tag=boomber.framework.block.doormat.pink_wool] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/pink_wool
execute if entity @s[tag=boomber.framework.block.doormat.gray_wool] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/gray_wool
execute if entity @s[tag=boomber.framework.block.doormat.light_gray_wool] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/light_gray_wool
execute if entity @s[tag=boomber.framework.block.doormat.cyan_wool] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/cyan_wool
execute if entity @s[tag=boomber.framework.block.doormat.purple_wool] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/purple_wool
execute if entity @s[tag=boomber.framework.block.doormat.blue_wool] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/blue_wool
execute if entity @s[tag=boomber.framework.block.doormat.brown_wool] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/brown_wool
execute if entity @s[tag=boomber.framework.block.doormat.green_wool] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/green_wool
execute if entity @s[tag=boomber.framework.block.doormat.red_wool] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/red_wool
execute if entity @s[tag=boomber.framework.block.doormat.black_wool] run loot spawn ~ ~ ~ loot boomber:framework/item/doormat/black_wool
kill @s