#> This function is generated by generator
execute if entity @e[tag=boomber.framework.trait.drawer, distance=..0.3] run function boomber:framework/trait/item_frame_block/block/drawer/oak/fail
execute unless entity @e[tag=boomber.framework.trait.drawer, distance=..0.3] run function boomber:framework/trait/item_frame_block/block/drawer/oak/success